// Code generated by "stringer -type=tokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[LEFT_PAREN-1]
	_ = x[RIGHT_PAREN-2]
	_ = x[LEFT_BRACE-3]
	_ = x[RIGHT_BRACE-4]
	_ = x[COMMA-5]
	_ = x[DOT-6]
	_ = x[MINUS-7]
	_ = x[PLUS-8]
	_ = x[SEMICOLON-9]
	_ = x[STAR-10]
	_ = x[EQUAL-11]
	_ = x[EQUAL_EQUAL-12]
	_ = x[BANG-13]
	_ = x[BANG_EQUAL-14]
	_ = x[LESS-15]
	_ = x[LESS_EQUAL-16]
	_ = x[GREATER-17]
	_ = x[GREATER_EQUAL-18]
	_ = x[SLASH-19]
	_ = x[COMMENT-20]
	_ = x[STRING-21]
	_ = x[AND-22]
	_ = x[CLASS-23]
	_ = x[ELSE-24]
	_ = x[FALSE-25]
	_ = x[FOR-26]
	_ = x[FUN-27]
	_ = x[IF-28]
	_ = x[NIL-29]
	_ = x[OR-30]
	_ = x[PRINT-31]
	_ = x[RETURN-32]
	_ = x[SUPER-33]
	_ = x[THIS-34]
	_ = x[TRUE-35]
	_ = x[VAR-36]
	_ = x[WHILE-37]
	_ = x[NUMBER-38]
	_ = x[IDENTIFIER-39]
}

const _tokenType_name = "EOFLEFT_PARENRIGHT_PARENLEFT_BRACERIGHT_BRACECOMMADOTMINUSPLUSSEMICOLONSTAREQUALEQUAL_EQUALBANGBANG_EQUALLESSLESS_EQUALGREATERGREATER_EQUALSLASHCOMMENTSTRINGANDCLASSELSEFALSEFORFUNIFNILORPRINTRETURNSUPERTHISTRUEVARWHILENUMBERIDENTIFIER"

var _tokenType_index = [...]uint8{0, 3, 13, 24, 34, 45, 50, 53, 58, 62, 71, 75, 80, 91, 95, 105, 109, 119, 126, 139, 144, 151, 157, 160, 165, 169, 174, 177, 180, 182, 185, 187, 192, 198, 203, 207, 211, 214, 219, 225, 235}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
